### ISSUE TITLE
Identify and Fix Broken Links

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#13]
**Description:** Ensure a seamless user experience by identifying and fixing any broken links on the website. Contributors will review the site's links and update or remove any links that no longer work.

- Difficulty: Easy
- Tags: Links, User Experience

**Comment by avelynhc** [comment]
@IshaanAdarsh Hi! I would like to work on this issue. Can you kindly assign this issue to me please? Thanks!

**Comment by IshaanAdarsh** [comment]
@avelynhc the links for the about, prof(header & footer) and alumni and strangers is not working along with some others. Start working on it right away.

**Comment by avelynhc** [comment]
@IshaanAdarsh Hi, is it possible to push the PR for this issue this weekend? I initially thought I would have time for it, but I have upcoming tests and an assignment due this week, which takes longer than I thought. However, I can dedicate time to it this weekend. Since this is my first code contribution, I'd prefer not to rush things. Thank you for your understanding.
